# This is a basic workflow to help you get started with Actions

name: CI-GitHubActions

# Controls when the workflow will run
on:
  push:
    branches: 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Print Hello Message Build
      run : echo "Hello from build job"
          
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Print Hello Message Deploy
      run : echo "Hello from deploy job"
