name: CI-GitHubActions
env:
  APP_NAME : "iFlask"
  PAC_NAME : "flask-deploy-ver-${{ github.sha }}"

# Controls when the workflow will run
on:
  push:
    branches: 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Print Hello Message Build
      run : echo "Hello from build job"
      
    - name: Execute few commands
      run : |
        echo "Message1"
        echo "Message2"
        echo "Application name: ${{ env.APP_NAME }}"
        
    - name: Git clone my repo
      uses: actions/checkout@v1
    
    - name: List current folder
      run : ls -la
          
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    env:
      VAR1: "This is job level variable1"
      VAR2: "This is job level variable2" 
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Print Hello Message Deploy
      run : echo "Hello from deploy job"
      
    - name: Print env vars
      run : |
        echo "Var1 = ${{ env.VAR1 }}"
        echo "Var2 = ${{ env.VAR2 }}"
        echo "Var3 = $LOCAL_VAR"
      env:
        LOCAL_VAR: "This is local environment variable"
      
    - name: Print Deployment Package
      run : echo "Deploy package name is ${{ env.PAC_NAME }}"
      
    - name: Lets test some packages if they are here 1
      run : aws --version
      
    - name: Lets test some packages if they are here 2
      run : zip --version
